### ISSUE TITLE
CI is not running

### ISSUE THREAD

**Issue by bsipocz** [RiceMunk/omnifit#29]
While I see a ``.travis.yml`` file, it seems that it has never run for this repository. While I acknowledge that you probably run the tests before releases, having a CI system that is integrated with GitHub can be extremely useful.

**Comment by RiceMunk** [comment]
You're right that I have always just run the tests manually instead of using CI stuff to do so. You're also right that setting up CI stuff to do it for me would make more sense.

I'll make a note of setting this up properly, when I find some time to do so.

**Comment by RiceMunk** [comment]
Just an update on this that I've poked at Travis to make it link up with omnifit now. Looks like it's failing repeatedly on the before_install steps, specifically with the bits under
`

    - export PYTHONIOENCODING=UTF8

    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh

    - chmod +x miniconda.sh

    - ./miniconda.sh -b
`
Error is "/home/travis/build.sh: line 57: conda: command not found", so looks like some lever somewhere has to be pulled to make anaconda work properly in Travis.
Making this note here to remind myself to look into it.

**Comment by bsipocz** [comment]
@RiceMunk - Well, the problem is that you while you update your ``PATH``, you don't install the conda environment in there, e.g. this should work:
```
bash miniconda.sh -b -p $HOME/miniconda
export PATH="$HOME/miniconda/bin:$PATH"
```

However in the last year or so the CI setups simplified a lot in the astropy package template with the introduction of  ``ci-helpers``. It takes case of setting up the environment and installing the dependencies. You may want to have a look at astropy core, or other astropy affiliates (e.g. photutils) for example travis files.
