### ISSUE TITLE
Website broken

### ISSUE THREAD

**Issue by astrofrog** [RiceMunk/omnifit#44]
The https://ricemunk.github.io/omnifit/ home page is returning a 404

**Comment by RiceMunk** [comment]
Well dang, looks like I might have accidentally deleted it a while back when I was doing some cleanup of old branches.
I'll look into either seeing if it's possible to restore it at some point, or just put up a new website.

**Comment by RiceMunk** [comment]
Fixed now; restored from an old copy I had lying around. I think it's the latest one.

Also added branch protection to the gh-pages branch, so I don't go and accidentally delete it again.
